mod assembled;
mod assembled_a;
mod assembled_b;
mod assembled_c;
mod assembled_d;
mod assembled_e;
mod assembled_f;
mod assembled_g;
mod assembled_h;
mod cppn;
mod cppn_2;
mod identity_mapping;
mod identity_mapping_b;
mod io_config;
mod jumper_connections;
mod layered_cppn;
mod layered_cppn_b;
mod layout;
mod layout_small;
mod layout_small_b;
mod local_connections;
mod module;
mod neat;
mod neat_b;
mod neat_c;
mod quad_tree;
mod single_cppn;
mod single_cppn_layout;

fn main() {
    assembled::create().save("outputs/assembled.tex");
    assembled_a::create().save("outputs/assembled_a.tex");
    assembled_b::create().save("outputs/assembled_b.tex");
    assembled_c::create().save("outputs/assembled_c.tex");
    assembled_d::create().save("outputs/assembled_d.tex");
    assembled_e::create().save("outputs/assembled_e.tex");
    assembled_f::create().save("outputs/assembled_f.tex");
    assembled_g::create().save("outputs/assembled_g.tex");
    assembled_h::create().save("outputs/assembled_h.tex");
    cppn::create().save("outputs/cppn.tex");
    cppn_2::create().save("outputs/cppn_2.tex");
    identity_mapping::create().save("outputs/identity_mapping.tex");
    identity_mapping_b::create().save("outputs/identity_mapping_b.tex");
    io_config::create().save("outputs/io_config.tex");
    jumper_connections::create().save("outputs/jumper_connections.tex");
    layered_cppn::create().save("outputs/layered_cppn.tex");
    layered_cppn_b::create().save("outputs/layered_cppn_b.tex");
    layout::create().save("outputs/layout.tex");
    layout_small::create().save("outputs/layout_small.tex");
    layout_small_b::create().save("outputs/layout_small_b.tex");
    local_connections::create().save("outputs/local_connections.tex");
    module::create().save("outputs/module.tex");
    neat::create().save("outputs/neat.tex");
    neat_b::create().save("outputs/neat_b.tex");
    neat_c::create().save("outputs/neat_c.tex");
    quad_tree::create().save("outputs/quad_tree.tex");
    single_cppn::create().save("outputs/single_cppn.tex");
    single_cppn_layout::create().save("outputs/single_cppn_layout.tex");
}
